default:
  retry: 2
  interruptible: true

stages:
  - test
  - build
  - deploy

cache: &global_cache
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor/
    - node_modules/
  policy: pull-push

phpunit_tests:
  image: php:8.3-fpm
  stage: test
  services:
    - name: mysql:5.7
      alias: db
      command: ['--default-authentication-plugin=mysql_native_password']
  variables:
    DB_HOST: db
    DB_DATABASE: laravel
    DB_USERNAME: root
    DB_PASSWORD: password
    MYSQL_DATABASE: laravel
    MYSQL_ROOT_PASSWORD: password
  cache:
    <<: *global_cache
  before_script:
    - apt-get update && apt-get install -y zip unzip git mariadb-client
    - docker-php-ext-install pdo_mysql
    - curl -sS https://getcomposer.org/installer | php
    - php composer.phar install --no-progress --no-interaction
    - cp .env.example .env
    - sed -i "s/LOG_CHANNEL=.*/LOG_CHANNEL=stack/" .env
    - sed -i "s/LOG_LEVEL=.*/LOG_LEVEL=debug/" .env
    - sed -i "s/DB_HOST=.*/DB_HOST=$DB_HOST/" .env
    - sed -i "s/DB_DATABASE=.*/DB_DATABASE=$DB_DATABASE/" .env
    - sed -i "s/DB_USERNAME=.*/DB_USERNAME=$DB_USERNAME/" .env
    - sed -i "s/DB_PASSWORD=.*/DB_PASSWORD=$DB_PASSWORD/" .env
    - php artisan key:generate
    - php artisan jwt:secret --force
    - echo "Waiting for MySQL..."
    - until mysql -h"$DB_HOST" -u"$DB_USERNAME" -p"$DB_PASSWORD" -e "SHOW DATABASES"; do sleep 5; done
    - php artisan migrate --force
  script:
    - php artisan test --testsuite=Feature
  rules:
    - changes:
        - app/**/*
        - tests/**/*
        - .gitlab-ci.yml

build_frontend:
  image: node:18-alpine
  stage: build
  cache:
    <<: *global_cache
  before_script:
    - npm ci
  script:
    - npm run build
  artifacts:
    paths:
      - public/build/
    expire_in: 1 week
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG

build_and_push_docker:
  image: docker:latest
  stage: deploy
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE:latest -f docker/php8.4/Dockerfile docker/php8.4/
    - docker push $CI_REGISTRY_IMAGE:latest
    - |
      if [ -n "$CI_COMMIT_TAG" ]; then
        docker tag $CI_REGISTRY_IMAGE:latest $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
        docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
      fi
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG
